  # feature Engineering  هندسة البيانات    

In [ ]:
#تحميل البيانات 
import pandas as pd
df= pd.read_csv("./data/houseprice.csv")

In [ ]:

# object_cols = list(df[df.select_dtypes("object")].index)
list(df.select_dtypes("object").columns)

['MSZoning',
 'Street',
 'Alley',
 'LotShape',
 'LandContour',
 'Utilities',
 'LotConfig',
 'LandSlope',
 'Neighborhood',
 'Condition1',
 'Condition2',
 'BldgType',
 'HouseStyle',
 'RoofStyle',
 'RoofMatl',
 'Exterior1st',
 'Exterior2nd',
 'MasVnrType',
 'ExterQual',
 'ExterCond',
 'Foundation',
 'BsmtQual',
 'BsmtCond',
 'BsmtExposure',
 'BsmtFinType1',
 'BsmtFinType2',
 'Heating',
 'HeatingQC',
 'CentralAir',
 'Electrical',
 'KitchenQual',
 'Functional',
 'FireplaceQu',
 'GarageType',
 'GarageFinish',
 'GarageQual',
 'GarageCond',
 'PavedDrive',
 'PoolQC',
 'Fence',
 'MiscFeature',
 'SaleType',
 'SaleCondition']

In [ ]:
df["TotalSF"] = df["GrLivArea"] + df["TotalBsmtSF"]
df["TotalPorchSF"] = df["OpenPorchSF"] + df["EnclosedPorch"] + df["3SsnPorch"] + df["ScreenPorch"]
df["TotalBath"] = df["FullBath"] + df["BsmtFullBath"] + 0.5 * (df["BsmtHalfBath"] + df["HalfBath"])

In [ ]:
#  حذف البيانات التي تم ادماجها   
df.drop(["GrLivArea", "TotalBsmtSF" , "OpenPorchSF", "EnclosedPorch", "3SsnPorch", "ScreenPorch" , "FullBath" , 
         "BsmtFullBath", "BsmtHalfBath", "HalfBath"  ], axis=1, inplace=True)

In [ ]:
df.head(4)

Id  MSSubClass MSZoning  LotFrontage  LotArea Street Alley LotShape  \
0   1          60       RL         65.0     8450   Pave   NaN      Reg   
1   2          20       RL         80.0     9600   Pave   NaN      Reg   
2   3          60       RL         68.0    11250   Pave   NaN      IR1   
3   4          70       RL         60.0     9550   Pave   NaN      IR1   

  LandContour Utilities LotConfig LandSlope Neighborhood Condition1  \
0         Lvl    AllPub    Inside       Gtl      CollgCr       Norm   
1         Lvl    AllPub       FR2       Gtl      Veenker      Feedr   
2         Lvl    AllPub    Inside       Gtl      CollgCr       Norm   
3         Lvl    AllPub    Corner       Gtl      Crawfor       Norm   

  Condition2 BldgType HouseStyle  OverallQual  OverallCond  YearBuilt  \
0       Norm     1Fam     2Story            7            5       2003   
1       Norm     1Fam     1Story            6            8       1976   
2       Norm     1Fam     2Story            7            5       2001   
3       Norm     1Fam     2Story            7            5       1915   

   YearRemodAdd RoofStyle RoofMatl Exterior1st Exterior2nd MasVnrType  \
0          2003     Gable  CompShg     VinylSd     VinylSd    BrkFace   
1          1976     Gable  CompShg     MetalSd     MetalSd       None   
2          2002     Gable  CompShg     VinylSd     VinylSd    BrkFace   
3          1970     Gable  CompShg     Wd Sdng     Wd Shng       None   

   MasVnrArea ExterQual ExterCond Foundation BsmtQual BsmtCond BsmtExposure  \
0       196.0        Gd        TA      PConc       Gd       TA           No   
1         0.0        TA        TA     CBlock       Gd       TA           Gd   
2       162.0        Gd        TA      PConc       Gd       TA           Mn   
3         0.0        TA        TA     BrkTil       TA       Gd           No   

  BsmtFinType1  BsmtFinSF1 BsmtFinType2  BsmtFinSF2  BsmtUnfSF Heating  \
0          GLQ         706          Unf           0        150    GasA   
1          ALQ         978          Unf           0        284    GasA   
2          GLQ         486          Unf           0        434    GasA   
3          ALQ         216          Unf           0        540    GasA   

  HeatingQC CentralAir Electrical  1stFlrSF  2ndFlrSF  LowQualFinSF  \
0        Ex          Y      SBrkr       856       854             0   
1        Ex          Y      SBrkr      1262         0             0   
2        Ex          Y      SBrkr       920       866             0   
3        Gd          Y      SBrkr       961       756             0   

   BedroomAbvGr  KitchenAbvGr KitchenQual  TotRmsAbvGrd Functional  \
0             3             1          Gd             8        Typ   
1             3             1          TA             6        Typ   
2             3             1          Gd             6        Typ   
3             3             1          Gd             7        Typ   

   Fireplaces FireplaceQu GarageType  GarageYrBlt GarageFinish  GarageCars  \
0           0         NaN     Attchd       2003.0          RFn           2   
1           1          TA     Attchd       1976.0          RFn           2   
2           1          TA     Attchd       2001.0          RFn           2   
3           1          Gd     Detchd       1998.0          Unf           3   

   GarageArea GarageQual GarageCond PavedDrive  WoodDeckSF  PoolArea PoolQC  \
0         548         TA         TA          Y           0         0    NaN   
1         460         TA         TA          Y         298         0    NaN   
2         608         TA         TA          Y           0         0    NaN   
3         642         TA         TA          Y           0         0    NaN   

  Fence MiscFeature  MiscVal  MoSold  YrSold SaleType SaleCondition  \
0   NaN         NaN        0       2    2008       WD        Normal   
1   NaN         NaN        0       5    2007       WD        Normal   
2   NaN         NaN        0       9    2008       WD        Normal   

## تحديد التصنيفات

In [ ]:
# تحديد المتغيرات التي تقل تصنيفاتها على 4 
for col in df.columns:
    if df[col].nunique()< 20:
        print(f" {col} :   {df[col].unique()} values " )

 MSSubClass :   [ 60  20  70  50 190  45  90 120  30  85  80 160  75 180  40] values 
 MSZoning :   ['RL' 'RM' 'C (all)' 'FV' 'RH'] values 
 Street :   ['Pave' 'Grvl'] values 
 Alley :   [nan 'Grvl' 'Pave'] values 
 LotShape :   ['Reg' 'IR1' 'IR2' 'IR3'] values 
 LandContour :   ['Lvl' 'Bnk' 'Low' 'HLS'] values 
 Utilities :   ['AllPub' 'NoSeWa'] values 
 LotConfig :   ['Inside' 'FR2' 'Corner' 'CulDSac' 'FR3'] values 
 LandSlope :   ['Gtl' 'Mod' 'Sev'] values 
 Condition1 :   ['Norm' 'Feedr' 'PosN' 'Artery' 'RRAe' 'RRNn' 'RRAn' 'PosA' 'RRNe'] values 
 Condition2 :   ['Norm' 'Artery' 'RRNn' 'Feedr' 'PosN' 'PosA' 'RRAn' 'RRAe'] values 
 BldgType :   ['1Fam' '2fmCon' 'Duplex' 'TwnhsE' 'Twnhs'] values 
 HouseStyle :   ['2Story' '1Story' '1.5Fin' '1.5Unf' 'SFoyer' 'SLvl' '2.5Unf' '2.5Fin'] values 
 OverallQual :   [ 7  6  8  5  9  4 10  3  1  2] values 
 OverallCond :   [5 8 6 7 4 2 3 9 1] values 
 RoofStyle :   ['Gable' 'Hip' 'Gambrel' 'Mansard' 'Flat' 'Shed'] values 
 RoofMatl :   ['CompS

-   تعديل المتغيرات التصنيفية 

(جميع البيانات التصنيفية التي لا ترتيب فيها سيتم ترميزها على شكل أعمدة )

In [ ]:
# تحديد المتغيرات الغير رقمية  والتي تقل تصنيفاتها على 20 
for col in df.select_dtypes(exclude="number").columns:
    if df[col].nunique()< 20:
        print(f" {col} :   {df[col].unique()} values " )
        # df[col]=df[col].astype("category")

 MSZoning :   ['RL' 'RM' 'C (all)' 'FV' 'RH'] values 
 Street :   ['Pave' 'Grvl'] values 
 Alley :   [nan 'Grvl' 'Pave'] values 
 LotShape :   ['Reg' 'IR1' 'IR2' 'IR3'] values 
 LandContour :   ['Lvl' 'Bnk' 'Low' 'HLS'] values 
 Utilities :   ['AllPub' 'NoSeWa'] values 
 LotConfig :   ['Inside' 'FR2' 'Corner' 'CulDSac' 'FR3'] values 
 LandSlope :   ['Gtl' 'Mod' 'Sev'] values 
 Condition1 :   ['Norm' 'Feedr' 'PosN' 'Artery' 'RRAe' 'RRNn' 'RRAn' 'PosA' 'RRNe'] values 
 Condition2 :   ['Norm' 'Artery' 'RRNn' 'Feedr' 'PosN' 'PosA' 'RRAn' 'RRAe'] values 
 BldgType :   ['1Fam' '2fmCon' 'Duplex' 'TwnhsE' 'Twnhs'] values 
 HouseStyle :   ['2Story' '1Story' '1.5Fin' '1.5Unf' 'SFoyer' 'SLvl' '2.5Unf' '2.5Fin'] values 
 RoofStyle :   ['Gable' 'Hip' 'Gambrel' 'Mansard' 'Flat' 'Shed'] values 
 RoofMatl :   ['CompShg' 'WdShngl' 'Metal' 'WdShake' 'Membran' 'Tar&Grv' 'Roll'
 'ClyTile'] values 
 Exterior1st :   ['VinylSd' 'MetalSd' 'Wd Sdng' 'HdBoard' 'BrkFace' 'WdShing' 'CemntBd'
 'Plywood' 'AsbShng' 

In [ ]:
# # تحديد المتغيرات الرقمية التي تقل تصنيفاتها على 4 
# for col in df.select_dtypes("number").columns:
#     if df[col].nunique()< 20:
#         print(f" {col} :   {df[col].unique()} values " )

In [ ]:

# MSSubClass متغير تصنيف العقار   
df.MSSubClass.unique()

array([ 60,  20,  70,  50, 190,  45,  90, 120,  30,  85,  80, 160,  75,
       180,  40])

In [ ]:
#  المتغيرات المرتبطة بالتواريخ
# YearBuilt, YearRemodAdd , MoSold, YrSold
print(df.MoSold.unique())
print(df.YrSold.unique())

[ 2  5  9 12 10  8 11  4  1  7  3  6]
[2008 2007 2006 2009 2010]


In [ ]:
# Processing category dtype is much faster to process
#تكون معالجة البيانات التصنيفية  اسرع

cols=["MSSubClass","YrSold" ]
df[cols]=df[cols].astype("category")

In [ ]:
df[cols].info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1460 entries, 0 to 1459
Data columns (total 2 columns):
 #   Column      Non-Null Count  Dtype   
---  ------      --------------  -----   
 0   MSSubClass  1460 non-null   category
 1   YrSold      1460 non-null   category
dtypes: category(2)
memory usage: 3.9 KB


_To better exploit any seasonality in SalePrice, we transform MoSold (which is a cyclical feature)_ 

In [ ]:
# http://blog.davidkaleko.com/feature-engineering-cyclical-features.html

import numpy as np
df["SnMoSold"] = np.sin(2 * np.pi * df.MoSold / 12)
df["CsMoSold"] = np.cos(2 * np.pi * df.MoSold / 12)
df.drop("MoSold", axis=1, inplace=True)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1460 entries, 0 to 1459
Data columns (total 75 columns):
 #   Column         Non-Null Count  Dtype   
---  ------         --------------  -----   
 0   Id             1460 non-null   int64   
 1   MSSubClass     1460 non-null   category
 2   MSZoning       1460 non-null   object  
 3   LotFrontage    1201 non-null   float64 
 4   LotArea        1460 non-null   int64   
 5   Street         1460 non-null   object  
 6   Alley          91 non-null     object  
 7   LotShape       1460 non-null   object  
 8   LandContour    1460 non-null   object  
 9   Utilities      1460 non-null   object  
 10  LotConfig      1460 non-null   object  
 11  LandSlope      1460 non-null   object  
 12  Neighborhood   1460 non-null   object  
 13  Condition1     1460 non-null   object  
 14  Condition2     1460 non-null   object  
 15  BldgType       1460 non-null   object  
 16  HouseStyle     1460 non-null   object  
 17  OverallQual    1460 non-null   in

In [ ]:
# حفظ البيانات
df.to_csv("housePrice1.csv")